aws_region        = "us-east-1"
environment       = "stage"
business_division = "HR"
vpc_name          = "myvpc"
cidr_block        = "10.0.0.0/16"
#vpc_availablity_zones    = ["us-east-1a", "us-east-1b"]
vpc_private_subnets      = ["10.0.1.0/24", "10.0.2.0/24"]
vpc_public_subnets       = ["10.0.101.0/24", "10.0.102.0/24"]
vpc_database_subnets     = ["10.0.151.0/24", "10.0.152.0/24"]
vpc_enable_nat_gateway   = true
vpc_single_nat_gateway   = true
vpc_enable_dns_hostnames = true
vpc_enable_dns_support   = true
instance_type            = "t2.micro"
aws-keypair1             = "sai_own"
cluster_name             = "eks-demo"